// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eypbmnritdshiiketlgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5cGJtbnJpdGRzaGlpa2V0bGdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNjQyOTgsImV4cCI6MjA3Mjk0MDI5OH0.5qxfiNYd5GWySrJ7EyW-VHAEoNB8aFzQrlOND6OU4to";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});